import { StyleSheet } from "react-native"

const css = StyleSheet.create({
      imageName:{
        flexDirection:'row',
        marginBottom:5,
        marginTop:5,
        alignContent:'center',
        marginBottom:'2%',
      },
      img:{
        marginTop:2.5,
        width:35,
        height:35,
        marginRight:6,
        alignSelf:'center',
        justifyContent:'center',
        alignContent:'center',
      },
      title:{
        alignSelf:'center',
        color:'#fff',
        fontSize:36,
      },
      containerForm:{
        width:'90%',
        height:'auto',
        margin:20,
        padding:15,
      },
      textForm:{
        alignContent:'center',
        color:'#fff',
        fontSize:28,
        marginBottom:2.5,
      },
      input:{
        width:'100%',
        borderRadius:12,
        backgroundColor:"#f6f6f6",
        height:40,
        marginBottom:5,
        paddingLeft:10,
        fontSize:18,
      },
      textButton:{
        alignSelf:'center',
        color:'#00ff00',
        fontSize:20,
        paddingBottom:'6%',
        paddingTop:'4%',
        alignContent:'center',
        justifyContent:'center',
      },
      button:{
        borderRadius:30,
        marginTop:20,
        width:'45%',
        borderColor:'#00ff00',
        borderWidth:2,
        alignSelf:'center',
        backgroundColor:'#fff',
      },
      messageErro:{
        fontSize:16,
        color:"#ffff22",
        fontWeight:"bold",
    },
    textAdm:{
      color:'#fff',
      fontSize:18,
    },
    voltar:{
        backgroundColor:'#6869AD',
        paddingTop:50,
        paddingLeft:30
    },
    buttonVoltar:{
        flexDirection:'row',
        width:'100%',
    },
    viewAdm:{
       marginTop:'30%',
        borderTopColor:'#fff',
        borderWidth:2,
        borderBottomColor:'#6869AD',
        borderLeftColor:'#6869AD',
        borderRightColor:'#6869AD',
    },
    viewAdm2:{
        marginTop:'60%',
        paddingTop:2,
        borderTopColor:'#fff',
        borderWidth:2,
        borderBottomColor:'#6869AD',
        borderLeftColor:'#6869AD',
        borderRightColor:'#6869AD',
    },
    erroLogin:{
      fontSize:20,
        color:"#ffff22",
        fontWeight:"bold",
    },
    erroDiv:{
      width:'100%',
      alignContent:'center',
      alignItems:'center',
      alignSelf:'center',
    },
});

export default css